### ISSUE TITLE
[Bug]: heroicon icons not loading

### ISSUE THREAD

**Issue by JanVDB2000** [ibrahimBougaoua/filament-sort-order#16]
### What happened?

The UpStepAction &  DownStepAction class was intended to have a fixed icon (heroicon-o-arrow-down). However, the icon was not being set when the make method was called. The issue was identified in the way the icon was being assigned within the class.

Error :

_**Type of IbrahimBougaoua\FilamentSortOrder\Actions\DownStepAction::$icon must be Illuminate\Contracts\Support\Htmlable|Closure|string|null (as in class Filament\Actions\StaticAction)**_

### How to reproduce the bug

when I load a pageResource where I use sort-order function 

```
 ->actions([
      DownStepAction::make(),
      UpStepAction::make(),
])
->defaultSort('sort_order', 'asc')
```

### Package Version

1.1.4

### PHP Version

8.2.0

### Laravel Version

11.16.0

### Which operating systems does with happen with?

Windows

### Notes

fix :

```

use Illuminate\Contracts\Support\Htmlable;

protected string | Htmlable | Closure | null $icon = 'heroicon-o-arrow-down';

```

**Comment by baken667** [comment]
same error!

**Comment by JanVDB2000** [comment]
same error after the solution I suggest? I also did a pull request and it works for me or not for you?

**Comment by JanVDB2000** [comment]
> same error!

same error after the solution I suggest? I also did a pull request and it works for me or not for you?

**Comment by battulga0719** [comment]
Laravel: 11.x
Filament: 3.2

Type of IbrahimBougaoua\FilamentSortOrder\Actions\UpStepAction::$icon must be Closure|string|null (as in class Filament\Actions\StaticAction)
