### ISSUE TITLE
[Question]: how should the config look for multiple tables ?

### ISSUE THREAD

**Issue by quasiperfect** [ibrahimBougaoua/filament-sort-order#2]
### What happened?

thanks for your work

sorry i opened a bug but there is no way to ask a question.

how should the config look for multiple tables or the packages supports only one ?

### How to reproduce the bug

not a bug

### Package Version

1.1

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by ibrahimBougaoua** [comment]
Yes, just add sort_order field to the table you want to affect.
Default table is users but you can add sort_order field to anuther table like post,category...etc,And use SortOrder for each model.

**Comment by quasiperfect** [comment]
thanks i will give it a try

**Comment by ibrahimBougaoua** [comment]
> thanks i will give it a try

Okey,thanks.
