### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mberneis** [ibrahimBougaoua/filament-sort-order#21]
### What happened?

I get the following error - It looks like there is already a pull request #19 to fix this:

![image](https://github.com/user-attachments/assets/416f7e6e-082f-4c7b-ac2a-0042035f2900)

### How to reproduce the bug

Add DownStepAction to Table Actions

### Package Version

1.1.4

### PHP Version

8.2.21

### Laravel Version

11.21.0

### Which operating systems does with happen with?

macOS

**Comment by ibrahimBougaoua** [comment]
**Thank you
This issue has been fixed.**
